# All inventory slots are zero-indexed (0 is the first slot).
menus:
  main:
    size: 18
    items:
      death:
        slot: 2
        material: SKELETON_SKULL
      world:
        slot: 4
        material: GRASS_BLOCK
      teleport:
        slot: 6
        material: ENDER_PEARL
      connection:
        slot: 12
        material: LIME_WOOL
      disconnection:
        slot: 14
        material: RED_WOOL
  death-list:
    size: 54
    record-item:
      material: BOOK
    slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
      - 36
      - 37
      - 38
      - 39
      - 40
      - 41
      - 42
      - 43
      - 44
    navigation:
      previous:
        slot: 45
        material: ARROW
      next:
        slot: 53
        material: ARROW
  death-detail:
    size: 54
    actions:
      restore:
        slot: 45
        material: LIME_WOOL
      erase:
        slot: 53
        material: RED_WOOL
    equipment-slots:
      offhand: 47
      boots: 48
      leggings: 49
      chestplate: 50
      helmet: 51
    content-slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
      - 25
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
      - 35
